### PR TITLE
Use rayon for parallel sort in graph_greedy_color

### PR DESCRIPTION
**Pull request by mtreinish**
This commit replaces the use of sort_by_key() with par_sort_by_key for
a parallelized version of the sort function. This should improve performance
of the sort which is one of the slower components of the function.

Partially addresses #86

### CODE REVIEW

**Comment by mtreinish** [comment]
I ran some quick comparison benchmarks using https://github.com/mtreinish/retworkx-bench and it is faster for a bunch of cases but regressed in a few too. So it's not a straight speed advantage:

```
Benchmarks that have improved:

       before           after         ratio
     [f47a95cf]       [899794e4]
     <parallel_sort_greedy_color~1>       <parallel_sort_greedy_color>
-         327±4ms          245±5ms     0.75  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 1)
-     24.7±0.09ms       17.6±0.4ms     0.71  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 100)
-         169±3ms          106±4ms     0.62  coloring.ColoringRoadMapNYC.time_graph_greedy_coloring
-      28.3±0.1ms       17.6±0.5ms     0.62  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 1000)
-      32.0±0.2ms       18.8±0.3ms     0.59  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 10000)
-         443±1ms          246±3ms     0.56  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 10)
-         500±4ms          246±3ms     0.49  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 100)
-         563±5ms          249±6ms     0.44  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 1000)
-         599±3ms          254±2ms     0.42  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 10000)
-         652±8ms          275±4ms     0.42  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 100000)

Benchmarks that have stayed the same:

       before           after         ratio
     [f47a95cf]       [899794e4]
     <parallel_sort_greedy_color~1>       <parallel_sort_greedy_color>
      8.32±0.05ms       8.91±0.1ms     1.07  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 100000)
      2.29±0.03ms      2.44±0.04ms     1.07  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 1000)
             134M             139M     1.03  coloring.ColoringRoadMapNYC.peakmem_graph_greedy_coloring
       10.1±0.3ms       10.3±0.1ms     1.01  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 1000000)
          254±9ms          255±6ms     1.00  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 1000000)
         8.51±0μs      8.50±0.01μs     1.00  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 1000)
       79.1±0.1μs      78.9±0.09μs     1.00  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 10000)
        792±0.8μs          790±1μs     1.00  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 100000)
      3.25±0.01ms      3.23±0.01ms     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 100000)
      30.5±0.06μs      30.2±0.03μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 1000)
        301±0.6μs          298±1μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 10000)
          672±4ns          665±6ns     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 10)
        284±0.7μs          281±2μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 10000)
         2.93±0ms      2.90±0.01ms     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 100000)
          181±4μs        179±0.2μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 100)
      6.90±0.04ms      6.83±0.01ms     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 100000)
         1.45±0μs      1.43±0.01μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 100)
          216±8ms          214±4ms     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 1000000)
          182±3μs        180±0.6μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 1000)
       43.7±0.4μs      43.2±0.08μs     0.99  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 1000)
          510±5μs          501±1μs     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 10000)
          209±7ms          205±3ms     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 1000000)
          145±4μs        142±0.2μs     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 10)
          615±7ns          602±3ns     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1, 1)
      4.98±0.02μs      4.87±0.01μs     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 100)
          127±4μs        124±0.1μs     0.98  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000, 1)
         46.7±2ms       45.5±0.7ms     0.97  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 1000000)
       15.4±0.3μs      15.0±0.05μs     0.97  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 10)
       12.8±0.3μs      12.4±0.03μs     0.97  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 1)
         67.6±2ms         65.5±1ms     0.97  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 1000000)
       17.6±0.3μs      17.0±0.05μs     0.97  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100, 100)
      2.45±0.01μs      2.35±0.01μs     0.96  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 10)
         2.08±0μs      1.99±0.02μs     0.95  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10, 1)
      26.4±0.09ms       24.9±0.5ms     0.94  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 100000)
         652±20ms          613±9ms     0.94  coloring.ColoringBenchmarks.time_graph_greedy_coloring(1000000, 1000000)
       18.2±0.1ms       16.6±0.4ms     0.91  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 1)
       21.2±0.1ms       17.8±0.7ms    ~0.84  coloring.ColoringBenchmarks.time_graph_greedy_coloring(100000, 10)

Benchmarks that have got worse:

       before           after         ratio
     [f47a95cf]       [899794e4]
     <parallel_sort_greedy_color~1>       <parallel_sort_greedy_color>
+     1.43±0.03ms      2.08±0.07ms     1.45  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 1)
+     1.59±0.02ms      2.07±0.02ms     1.30  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 10)
+     2.12±0.02ms      2.50±0.06ms     1.18  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 10000)
+     1.88±0.03ms      2.19±0.02ms     1.16  coloring.ColoringBenchmarks.time_graph_greedy_coloring(10000, 100)
```

@t-imamichi what do you think?

**Comment by mtreinish** [comment]
So I took a look at the input graph that retworkx-bench is generating for the `ColoringBenchmarks` benchmarks and it's probably a worst case example for the stable sort: https://blog.kortar.org/wp-content/uploads/2020/08/graph.svg basically everything has an equal edge count which probably means that the parallel overhead for the sort stability is coming into play heavily: https://docs.rs/rayon/1.3.1/rayon/slice/trait.ParallelSliceMut.html#method.par_sort_by_key. The `ColoringRoadMapNYC` example is a more realistic use case as it's a simplified graph of the NYC road maps from the 9th DIMACS challenge and there is a noticeable speedup there.

I'm going to try creating an isolated benchmark from aqua's `AbelianGrouper` to compare this on that use case, because that's where this really matters. If there is a good speedup there I think this is good to go, the regression in those synthetic cases aren't a super big deal because I doubt anyone is going to use the coloring function on a weird input graph like that.

**Comment by t-imamichi** [comment]
It looks good. I tried it with the master of Aqua with [my script](https://gist.github.com/t-imamichi/354de0fc2e0731f1d7fe0b62ef91db34) with [my branch](https://github.com/t-imamichi/qiskit-aqua/tree/rx-color)
I checked the computation time with NH3 JW. I don't think the coloring is the bottleneck now. 

- Aqua master default (no retworkx): 9.25 sec
- retworkx 0.4.0: 7.54 sec
- this PR: 7.08 sec

**Comment by mtreinish** [comment]
Ok cool, then lets go with this. I've been keen to get some parallelism into retworkx (even if just a little) because it's one of the advantages of being in rust that we can use threads without the gil. This looks like it'll be a good starting point. Thanks for checking it.

**Pull request merged**
